#!/usr/bin/env python3

import sys

WORDS = {-1: 'nålla',
         0: '',
         1: 'okta',
         2: 'guokte',
         3: 'golbma',
         4: 'njeallje',
         5: 'vihtta',
         6: 'guhhta',
         7: 'čieža',
         8: 'gávcci',
         9: 'ovcci',
         10: 'logi',
         -10: 'nuppelohkái',
         100: 'čuođi',
         1000: 'duhát',
         }


def get_number_below_hundred(number):
    assert 0 <= number < 100
    if number <= 10:
        return WORDS[number]
    if 11 <= number < 20:
        return WORDS[number % 10] + WORDS[-10]
    return WORDS[number // 10] + WORDS[10] + WORDS[number % 10]


def get_number_below_thousand(number):
    assert 100 <= number < 1000
    w = ""
    if number >= 200:
        w += WORDS[number // 100]
    w += WORDS[100]
    w += get_number_below_hundred(number % 100)
    return w


def get_number_below_tenthousand(number):
    assert 1000 <= number < 10000

    w1 = ""
    if number >= 2000:
        w1 += WORDS[number // 1000]
    w1 += WORDS[1000]
    w1 += get_number_below_thousand(number % 1000)

    w2 = get_number_below_hundred(number // 100) + WORDS[100] + get_number_below_hundred(number % 100)

    return [w1, w2]


for number in sys.stdin:
    number = number.strip()

    if len(number) > 6:
        exit("Too big number: {}".format(number))

    while len(number) > 0 and number[0] == '0':
        print(WORDS[-1], end="")
        number = number[1:]
    if len(number) == 0:
        continue

    number = int(number)

    if number < 100:
        print(get_number_below_hundred(number))
    elif number < 1000:
        print(get_number_below_thousand(number))
    elif number < 10000:
        options = get_number_below_tenthousand(number)
        print(",".join(options))
